name: React CI

on:
  push:
    branches:
      - main
    paths:
      - "fagnoon_frontend/**"
  pull_request:
    branches:
      - main
    paths:
      - "fagnoon_frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./fagnoon_frontend

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "18" # Or your project's Node.js version

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build
      env:
        VITE_API_URL: ${{ secrets.VITE_API_URL }} # Example if you need API URL during build

    # Optional: Add steps for linting and testing if configured
    # - name: Lint
    #   run: npm run lint

    # - name: Test
    #   run: npm run test

